window.ENERGY_MIX_DATA = {
  "generatedAt": "2026-07-09T04:37:30Z",
  "source": {
    "energy": "https://raw.githubusercontent.com/owid/energy-data/master/owid-energy-data.csv",
    "geography": "https://raw.githubusercontent.com/mledoze/countries/master/countries.json",
    "note": "Latest available electricity-generation source shares per country from OWID energy data; geography from REST Countries. Shares normalized to 100% for gameplay.",
    "minGenerationTwh": 2.0
  },
  "categories": [
    "coal",
    "gas",
    "oil",
    "nuclear",
    "hydro",
    "wind",
    "solar",
    "biofuel",
    "otherRenewables"
  ],
  "countries": [
    {
      "name": "Albania",
      "iso": "ALB",
      "year": 2024,
      "generationTwh": 8.3,
      "mix": {
        "coal": 0.0,
        "gas": 0.0,
        "oil": 0.0,
        "nuclear": 0.0,
        "hydro": 95.9,
        "wind": 0.0,
        "solar": 4.1,
        "biofuel": 0.0,
        "otherRenewables": 0.0
      },
      "region": "Europe",
      "subregion": "Southeast Europe",
      "lat": 41.0,
      "lng": 20.0,
      "restName": "Albania"
    },
    {
      "name": "Algeria",
      "iso": "DZA",
      "year": 2024,
      "generationTwh": 96.4,
      "mix": {
        "coal": 0.0,
        "gas": 98.7,
        "oil": 0.3,
        "nuclear": 0.0,
        "hydro": 0.0,
        "wind": 0.0,
        "solar": 1.0,
        "biofuel": 0.0,
        "otherRenewables": 0.0
      },
      "region": "Africa",
      "subregion": "Northern Africa",
      "lat": 28.0,
      "lng": 3.0,
      "restName": "Algeria"
    },
    {
      "name": "Angola",
      "iso": "AGO",
      "year": 2024,
      "generationTwh": 15.6,
      "mix": {
        "coal": 0.0,
        "gas": 9.0,
        "oil": 17.3,
        "nuclear": 0.0,
        "hydro": 70.6,
        "wind": 0.0,
        "solar": 2.8,
        "biofuel": 0.3,
        "otherRenewables": 0.0
      },
      "region": "Africa",
      "subregion": "Middle Africa",
      "lat": -12.5,
      "lng": 18.5,
      "restName": "Angola"
    },
    {
      "name": "Argentina",
      "iso": "ARG",
      "year": 2025,
      "generationTwh": 153.2,
      "mix": {
        "coal": 1.8,
        "gas": 52.7,
        "oil": 3.9,
        "nuclear": 7.0,
        "hydro": 17.1,
        "wind": 12.2,
        "solar": 3.4,
        "biofuel": 1.9,
        "otherRenewables": 0.0
      },
      "region": "Americas",
      "subregion": "South America",
      "lat": -34.0,
      "lng": -64.0,
      "restName": "Argentina"
    },
    {
      "name": "Armenia",
      "iso": "ARM",
      "year": 2025,
      "generationTwh": 9.7,
      "mix": {
        "coal": 0.0,
        "gas": 34.0,
        "oil": 0.0,
        "nuclear": 27.0,
        "hydro": 28.0,
        "wind": 0.0,
        "solar": 11.0,
        "biofuel": 0.0,
        "otherRenewables": 0.0
      },
      "region": "Asia",
      "subregion": "Western Asia",
      "lat": 40.0,
      "lng": 45.0,
      "restName": "Armenia"
    },
    {
      "name": "Australia",
      "iso": "AUS",
      "year": 2025,
      "generationTwh": 286.3,
      "mix": {
        "coal": 42.7,
        "gas": 16.4,
        "oil": 2.2,
        "nuclear": 0.0,
        "hydro": 4.3,
        "wind": 13.7,
        "solar": 19.6,
        "biofuel": 1.1,
        "otherRenewables": 0.0
      },
      "region": "Oceania",
      "subregion": "Australia and New Zealand",
      "lat": -27.0,
      "lng": 133.0,
      "restName": "Australia"
    },
    {
      "name": "Austria",
      "iso": "AUT",
      "year": 2025,
      "generationTwh": 73.2,
      "mix": {
        "coal": 0.0,
        "gas": 11.9,
        "oil": 4.5,
        "nuclear": 0.0,
        "hydro": 51.8,
        "wind": 11.3,
        "solar": 14.1,
        "biofuel": 6.4,
        "otherRenewables": 0.0
      },
      "region": "Europe",
      "subregion": "Central Europe",
      "lat": 47.33333333,
      "lng": 13.33333333,
      "restName": "Austria"
    },
    {
      "name": "Azerbaijan",
      "iso": "AZE",
      "year": 2025,
      "generationTwh": 28.1,
      "mix": {
        "coal": 0.0,
        "gas": 87.6,
        "oil": 0.2,
        "nuclear": 0.0,
        "hydro": 11.5,
        "wind": 0.3,
        "solar": 0.0,
        "biofuel": 0.4,
        "otherRenewables": 0.0
      },
      "region": "Asia",
      "subregion": "Western Asia",
      "lat": 40.5,
      "lng": 47.5,
      "restName": "Azerbaijan"
    },
    {
      "name": "Bahamas",
      "iso": "BHS",
      "year": 2024,
      "generationTwh": 2.2,
      "mix": {
        "coal": 0.0,
        "gas": 0.0,
        "oil": 99.1,
        "nuclear": 0.0,
        "hydro": 0.0,
        "wind": 0.0,
        "solar": 0.9,
        "biofuel": 0.0,
        "otherRenewables": 0.0
      },
      "region": "Americas",
      "subregion": "Caribbean",
      "lat": 24.25,
      "lng": -76.0,
      "restName": "Bahamas"
    },
    {
      "name": "Bahrain",
      "iso": "BHR",
      "year": 2024,
      "generationTwh": 38.0,
      "mix": {
        "coal": 0.0,
        "gas": 99.7,
        "oil": 0.0,
        "nuclear": 0.0,
        "hydro": 0.0,
        "wind": 0.0,
        "solar": 0.3,
        "biofuel": 0.0,
        "otherRenewables": 0.0
      },
      "region": "Asia",
      "subregion": "Western Asia",
      "lat": 26.0,
      "lng": 50.55,
      "restName": "Bahrain"
    },
    {
      "name": "Bangladesh",
      "iso": "BGD",
      "year": 2025,
      "generationTwh": 103.4,
      "mix": {
        "coal": 21.5,
        "gas": 64.3,
        "oil": 12.1,
        "nuclear": 0.0,
        "hydro": 0.6,
        "wind": 0.0,
        "solar": 1.5,
        "biofuel": 0.0,
        "otherRenewables": 0.0
      },
      "region": "Asia",
      "subregion": "Southern Asia",
      "lat": 24.0,
      "lng": 90.0,
      "restName": "Bangladesh"
    },
    {
      "name": "Belarus",
      "iso": "BLR",
      "year": 2025,
      "generationTwh": 46.4,
      "mix": {
        "coal": 0.0,
        "gas": 54.6,
        "oil": 4.0,
        "nuclear": 36.6,
        "hydro": 2.0,
        "wind": 1.0,
        "solar": 0.8,
        "biofuel": 1.0,
        "otherRenewables": 0.0
      },
      "region": "Europe",
      "subregion": "Eastern Europe",
      "lat": 53.0,
      "lng": 28.0,
      "restName": "Belarus"
    },
    {
      "name": "Belgium",
      "iso": "BEL",
      "year": 2025,
      "generationTwh": 72.9,
      "mix": {
        "coal": 0.0,
        "gas": 21.5,
        "oil": 6.4,
        "nuclear": 33.2,
        "hydro": 0.6,
        "wind": 18.8,
        "solar": 14.3,
        "biofuel": 5.2,
        "otherRenewables": 0.0
      },
      "region": "Europe",
      "subregion": "Western Europe",
      "lat": 50.83333333,
      "lng": 4.0,
      "restName": "Belgium"
    },
    {
      "name": "Bhutan",
      "iso": "BTN",
      "year": 2024,
      "generationTwh": 11.0,
      "mix": {
        "coal": 0.0,
        "gas": 0.0,
        "oil": 0.0,
        "nuclear": 0.0,
        "hydro": 100.0,
        "wind": 0.0,
        "solar": 0.0,
        "biofuel": 0.0,
        "otherRenewables": 0.0
      },
      "region": "Asia",
      "subregion": "Southern Asia",
      "lat": 27.5,
      "lng": 90.5,
      "restName": "Bhutan"
    },
    {
      "name": "Bolivia",
      "iso": "BOL",
      "year": 2025,
      "generationTwh": 13.6,
      "mix": {
        "coal": 0.0,
        "gas": 62.4,
        "oil": 1.5,
        "nuclear": 0.0,
        "hydro": 27.9,
        "wind": 2.1,
        "solar": 2.9,
        "biofuel": 3.2,
        "otherRenewables": 0.0
      },
      "region": "Americas",
      "subregion": "South America",
      "lat": -17.0,
      "lng": -65.0,
      "restName": "Bolivia"
    },
    {
      "name": "Bosnia and Herzegovina",
      "iso": "BIH",
      "year": 2025,
      "generationTwh": 14.4,
      "mix": {
        "coal": 55.4,
        "gas": 0.0,
        "oil": 1.0,
        "nuclear": 0.0,
        "hydro": 36.6,
        "wind": 2.6,
        "solar": 4.1,
        "biofuel": 0.3,
        "otherRenewables": 0.0
      },
      "region": "Europe",
      "subregion": "Southeast Europe",
      "lat": 44.0,
      "lng": 18.0,
      "restName": "Bosnia and Herzegovina"
    },
    {
      "name": "Botswana",
      "iso": "BWA",
      "year": 2024,
      "generationTwh": 3.4,
      "mix": {
        "coal": 98.2,
        "gas": 0.0,
        "oil": 1.5,
        "nuclear": 0.0,
        "hydro": 0.0,
        "wind": 0.0,
        "solar": 0.3,
        "biofuel": 0.0,
        "otherRenewables": 0.0
      },
      "region": "Africa",
      "subregion": "Southern Africa",
      "lat": -22.0,
      "lng": 24.0,
      "restName": "Botswana"
    },
    {
      "name": "Brazil",
      "iso": "BRA",
      "year": 2025,
      "generationTwh": 750.5,
      "mix": {
        "coal": 2.3,
        "gas": 7.3,
        "oil": 1.7,
        "nuclear": 2.1,
        "hydro": 51.8,
        "wind": 15.7,
        "solar": 11.8,
        "biofuel": 7.3,
        "otherRenewables": 0.0
      },
      "region": "Americas",
      "subregion": "South America",
      "lat": -10.0,
      "lng": -55.0,
      "restName": "Brazil"
    },
    {
      "name": "Brunei",
      "iso": "BRN",
      "year": 2024,
      "generationTwh": 5.6,
      "mix": {
        "coal": 19.8,
        "gas": 79.1,
        "oil": 0.9,
        "nuclear": 0.0,
        "hydro": 0.0,
        "wind": 0.0,
        "solar": 0.2,
        "biofuel": 0.0,
        "otherRenewables": 0.0
      },
      "region": "Asia",
      "subregion": "South-Eastern Asia",
      "lat": 4.5,
      "lng": 114.66666666,
      "restName": "Brunei"
    },
    {
      "name": "Bulgaria",
      "iso": "BGR",
      "year": 2025,
      "generationTwh": 38.0,
      "mix": {
        "coal": 22.5,
        "gas": 4.9,
        "oil": 0.7,
        "nuclear": 39.0,
        "hydro": 6.7,
        "wind": 3.5,
        "solar": 18.2,
        "biofuel": 4.5,
        "otherRenewables": 0.0
      },
      "region": "Europe",
      "subregion": "Southeast Europe",
      "lat": 43.0,
      "lng": 25.0,
      "restName": "Bulgaria"
    },
    {
      "name": "Cambodia",
      "iso": "KHM",
      "year": 2025,
      "generationTwh": 17.8,
      "mix": {
        "coal": 56.7,
        "gas": 0.0,
        "oil": 2.5,
        "nuclear": 0.0,
        "hydro": 29.9,
        "wind": 0.0,
        "solar": 10.6,
        "biofuel": 0.3,
        "otherRenewables": 0.0
      },
      "region": "Asia",
      "subregion": "South-Eastern Asia",
      "lat": 13.0,
      "lng": 105.0,
      "restName": "Cambodia"
    },
    {
      "name": "Cameroon",
      "iso": "CMR",
      "year": 2024,
      "generationTwh": 7.3,
      "mix": {
        "coal": 0.0,
        "gas": 22.0,
        "oil": 4.8,
        "nuclear": 0.0,
        "hydro": 72.0,
        "wind": 0.0,
        "solar": 0.6,
        "biofuel": 0.6,
        "otherRenewables": 0.0
      },
      "region": "Africa",
      "subregion": "Middle Africa",
      "lat": 6.0,
      "lng": 12.0,
      "restName": "Cameroon"
    },
    {
      "name": "Canada",
      "iso": "CAN",
      "year": 2025,
      "generationTwh": 652.4,
      "mix": {
        "coal": 4.1,
        "gas": 17.8,
        "oil": 1.2,
        "nuclear": 13.1,
        "hydro": 52.7,
        "wind": 7.9,
        "solar": 1.6,
        "biofuel": 1.6,
        "otherRenewables": 0.0
      },
      "region": "Americas",
      "subregion": "North America",
      "lat": 60.0,
      "lng": -95.0,
      "restName": "Canada"
    },
    {
      "name": "Chile",
      "iso": "CHL",
      "year": 2025,
      "generationTwh": 88.5,
      "mix": {
        "coal": 17.8,
        "gas": 15.3,
        "oil": 0.6,
        "nuclear": 0.0,
        "hydro": 22.2,
        "wind": 13.1,
        "solar": 25.0,
        "biofuel": 5.7,
        "otherRenewables": 0.3
      },
      "region": "Americas",
      "subregion": "South America",
      "lat": -30.0,
      "lng": -71.0,
      "restName": "Chile"
    },
    {
      "name": "China",
      "iso": "CHN",
      "year": 2025,
      "generationTwh": 10583.4,
      "mix": {
        "coal": 54.4,
        "gas": 3.2,
        "oil": 0.8,
        "nuclear": 4.6,
        "hydro": 13.2,
        "wind": 10.7,
        "solar": 11.1,
        "biofuel": 2.0,
        "otherRenewables": 0.0
      },
      "region": "Asia",
      "subregion": "Eastern Asia",
      "lat": 35.0,
      "lng": 105.0,
      "restName": "China"
    },
    {
      "name": "Colombia",
      "iso": "COL",
      "year": 2025,
      "generationTwh": 90.4,
      "mix": {
        "coal": 6.1,
        "gas": 13.8,
        "oil": 3.1,
        "nuclear": 0.0,
        "hydro": 69.1,
        "wind": 0.2,
        "solar": 5.1,
        "biofuel": 2.6,
        "otherRenewables": 0.0
      },
      "region": "Americas",
      "subregion": "South America",
      "lat": 4.0,
      "lng": -72.0,
      "restName": "Colombia"
    },
    {
      "name": "Congo",
      "iso": "COG",
      "year": 2024,
      "generationTwh": 5.5,
      "mix": {
        "coal": 0.0,
        "gas": 73.9,
        "oil": 5.3,
        "nuclear": 0.0,
        "hydro": 20.1,
        "wind": 0.0,
        "solar": 0.2,
        "biofuel": 0.5,
        "otherRenewables": 0.0
      },
      "region": "Africa",
      "subregion": "Middle Africa",
      "lat": -1.0,
      "lng": 15.0,
      "restName": "Congo"
    },
    {
      "name": "Costa Rica",
      "iso": "CRI",
      "year": 2025,
      "generationTwh": 12.8,
      "mix": {
        "coal": 0.0,
        "gas": 0.0,
        "oil": 0.0,
        "nuclear": 0.0,
        "hydro": 74.8,
        "wind": 12.1,
        "solar": 0.7,
        "biofuel": 0.5,
        "otherRenewables": 11.9
      },
      "region": "Americas",
      "subregion": "Central America",
      "lat": 10.0,
      "lng": -84.0,
      "restName": "Costa Rica"
    },
    {
      "name": "Cote d'Ivoire",
      "iso": "CIV",
      "year": 2024,
      "generationTwh": 10.8,
      "mix": {
        "coal": 0.0,
        "gas": 70.9,
        "oil": 0.2,
        "nuclear": 0.0,
        "hydro": 27.8,
        "wind": 0.0,
        "solar": 0.2,
        "biofuel": 0.9,
        "otherRenewables": 0.0
      },
      "region": "Africa",
      "subregion": "Western Africa",
      "lat": 8.0,
      "lng": -5.0,
      "restName": "Ivory Coast"
    },
    {
      "name": "Croatia",
      "iso": "HRV",
      "year": 2025,
      "generationTwh": 14.7,
      "mix": {
        "coal": 5.0,
        "gas": 18.8,
        "oil": 0.0,
        "nuclear": 0.0,
        "hydro": 39.2,
        "wind": 21.4,
        "solar": 8.8,
        "biofuel": 6.8,
        "otherRenewables": 0.0
      },
      "region": "Europe",
      "subregion": "Southeast Europe",
      "lat": 45.16666666,
      "lng": 15.5,
      "restName": "Croatia"
    },
    {
      "name": "Cuba",
      "iso": "CUB",
      "year": 2024,
      "generationTwh": 19.4,
      "mix": {
        "coal": 0.0,
        "gas": 13.6,
        "oil": 82.4,
        "nuclear": 0.0,
        "hydro": 0.6,
        "wind": 0.4,
        "solar": 1.2,
        "biofuel": 1.8,
        "otherRenewables": 0.0
      },
      "region": "Americas",
      "subregion": "Caribbean",
      "lat": 21.5,
      "lng": -80.0,
      "restName": "Cuba"
    },
    {
      "name": "Cyprus",
      "iso": "CYP",
      "year": 2025,
      "generationTwh": 5.9,
      "mix": {
        "coal": 0.0,
        "gas": 0.0,
        "oil": 72.2,
        "nuclear": 0.0,
        "hydro": 0.0,
        "wind": 3.6,
        "solar": 23.2,
        "biofuel": 1.0,
        "otherRenewables": 0.0
      },
      "region": "Europe",
      "subregion": "Southern Europe",
      "lat": 35.0,
      "lng": 33.0,
      "restName": "Cyprus"
    },
    {
      "name": "Czechia",
      "iso": "CZE",
      "year": 2025,
      "generationTwh": 75.5,
      "mix": {
        "coal": 35.2,
        "gas": 5.4,
        "oil": 0.2,
        "nuclear": 42.3,
        "hydro": 2.3,
        "wind": 0.8,
        "solar": 5.8,
        "biofuel": 8.0,
        "otherRenewables": 0.0
      },
      "region": "Europe",
      "subregion": "Central Europe",
      "lat": 49.75,
      "lng": 15.5,
      "restName": "Czechia"
    },
    {
      "name": "Democratic Republic of Congo",
      "iso": "COD",
      "year": 2024,
      "generationTwh": 15.9,
      "mix": {
        "coal": 0.0,
        "gas": 0.0,
        "oil": 0.0,
        "nuclear": 0.0,
        "hydro": 84.1,
        "wind": 0.0,
        "solar": 15.8,
        "biofuel": 0.1,
        "otherRenewables": 0.0
      },
      "region": "Africa",
      "subregion": "Middle Africa",
      "lat": 0.0,
      "lng": 25.0,
      "restName": "DR Congo"
    },
    {
      "name": "Denmark",
      "iso": "DNK",
      "year": 2025,
      "generationTwh": 33.3,
      "mix": {
        "coal": 2.7,
        "gas": 2.4,
        "oil": 3.7,
        "nuclear": 0.0,
        "hydro": 0.1,
        "wind": 57.6,
        "solar": 13.4,
        "biofuel": 20.1,
        "otherRenewables": 0.0
      },
      "region": "Europe",
      "subregion": "Northern Europe",
      "lat": 56.0,
      "lng": 10.0,
      "restName": "Denmark"
    },
    {
      "name": "Dominican Republic",
      "iso": "DOM",
      "year": 2025,
      "generationTwh": 22.7,
      "mix": {
        "coal": 29.0,
        "gas": 26.8,
        "oil": 20.4,
        "nuclear": 0.0,
        "hydro": 6.7,
        "wind": 6.3,
        "solar": 9.9,
        "biofuel": 0.9,
        "otherRenewables": 0.0
      },
      "region": "Americas",
      "subregion": "Caribbean",
      "lat": 19.0,
      "lng": -70.66666666,
      "restName": "Dominican Republic"
    },
    {
      "name": "Ecuador",
      "iso": "ECU",
      "year": 2025,
      "generationTwh": 36.6,
      "mix": {
        "coal": 0.0,
        "gas": 2.7,
        "oil": 17.9,
        "nuclear": 0.0,
        "hydro": 77.9,
        "wind": 0.5,
        "solar": 0.1,
        "biofuel": 0.9,
        "otherRenewables": 0.0
      },
      "region": "Americas",
      "subregion": "South America",
      "lat": -2.0,
      "lng": -77.5,
      "restName": "Ecuador"
    },
    {
      "name": "Egypt",
      "iso": "EGY",
      "year": 2025,
      "generationTwh": 245.7,
      "mix": {
        "coal": 0.0,
        "gas": 79.6,
        "oil": 7.4,
        "nuclear": 0.0,
        "hydro": 6.1,
        "wind": 3.8,
        "solar": 3.1,
        "biofuel": 0.0,
        "otherRenewables": 0.0
      },
      "region": "Africa",
      "subregion": "Northern Africa",
      "lat": 27.0,
      "lng": 30.0,
      "restName": "Egypt"
    },
    {
      "name": "El Salvador",
      "iso": "SLV",
      "year": 2025,
      "generationTwh": 6.5,
      "mix": {
        "coal": 0.0,
        "gas": 0.0,
        "oil": 13.5,
        "nuclear": 0.0,
        "hydro": 30.3,
        "wind": 3.1,
        "solar": 20.3,
        "biofuel": 12.1,
        "otherRenewables": 20.7
      },
      "region": "Americas",
      "subregion": "Central America",
      "lat": 13.83333333,
      "lng": -88.91666666,
      "restName": "El Salvador"
    },
    {
      "name": "Estonia",
      "iso": "EST",
      "year": 2025,
      "generationTwh": 6.1,
      "mix": {
        "coal": 0.0,
        "gas": 1.3,
        "oil": 39.1,
        "nuclear": 0.0,
        "hydro": 0.5,
        "wind": 18.8,
        "solar": 18.5,
        "biofuel": 21.8,
        "otherRenewables": 0.0
      },
      "region": "Europe",
      "subregion": "Northern Europe",
      "lat": 59.0,
      "lng": 26.0,
      "restName": "Estonia"
    },
    {
      "name": "Ethiopia",
      "iso": "ETH",
      "year": 2025,
      "generationTwh": 33.4,
      "mix": {
        "coal": 0.0,
        "gas": 0.0,
        "oil": 0.0,
        "nuclear": 0.0,
        "hydro": 96.5,
        "wind": 3.3,
        "solar": 0.1,
        "biofuel": 0.0,
        "otherRenewables": 0.1
      },
      "region": "Africa",
      "subregion": "Eastern Africa",
      "lat": 8.0,
      "lng": 38.0,
      "restName": "Ethiopia"
    },
    {
      "name": "Finland",
      "iso": "FIN",
      "year": 2025,
      "generationTwh": 82.3,
      "mix": {
        "coal": 0.2,
        "gas": 1.2,
        "oil": 2.3,
        "nuclear": 39.8,
        "hydro": 15.1,
        "wind": 27.4,
        "solar": 1.2,
        "biofuel": 12.6,
        "otherRenewables": 0.2
      },
      "region": "Europe",
      "subregion": "Northern Europe",
      "lat": 64.0,
      "lng": 26.0,
      "restName": "Finland"
    },
    {
      "name": "France",
      "iso": "FRA",
      "year": 2025,
      "generationTwh": 570.0,
      "mix": {
        "coal": 0.3,
        "gas": 3.0,
        "oil": 1.8,
        "nuclear": 68.8,
        "hydro": 10.4,
        "wind": 8.2,
        "solar": 5.6,
        "biofuel": 1.8,
        "otherRenewables": 0.1
      },
      "region": "Europe",
      "subregion": "Western Europe",
      "lat": 46.0,
      "lng": 2.0,
      "restName": "France"
    },
    {
      "name": "Gabon",
      "iso": "GAB",
      "year": 2024,
      "generationTwh": 2.6,
      "mix": {
        "coal": 0.0,
        "gas": 44.2,
        "oil": 20.4,
        "nuclear": 0.0,
        "hydro": 35.0,
        "wind": 0.0,
        "solar": 0.0,
        "biofuel": 0.4,
        "otherRenewables": 0.0
      },
      "region": "Africa",
      "subregion": "Middle Africa",
      "lat": -1.0,
      "lng": 11.75,
      "restName": "Gabon"
    },
    {
      "name": "Georgia",
      "iso": "GEO",
      "year": 2025,
      "generationTwh": 13.5,
      "mix": {
        "coal": 0.0,
        "gas": 20.4,
        "oil": 0.0,
        "nuclear": 0.0,
        "hydro": 78.8,
        "wind": 0.6,
        "solar": 0.2,
        "biofuel": 0.0,
        "otherRenewables": 0.0
      },
      "region": "Asia",
      "subregion": "Western Asia",
      "lat": 42.0,
      "lng": 43.5,
      "restName": "Georgia"
    },
    {
      "name": "Germany",
      "iso": "DEU",
      "year": 2025,
      "generationTwh": 500.5,
      "mix": {
        "coal": 20.6,
        "gas": 16.5,
        "oil": 3.8,
        "nuclear": 0.0,
        "hydro": 3.9,
        "wind": 27.2,
        "solar": 17.9,
        "biofuel": 10.1,
        "otherRenewables": 0.0
      },
      "region": "Europe",
      "subregion": "Western Europe",
      "lat": 51.0,
      "lng": 9.0,
      "restName": "Germany"
    },
    {
      "name": "Ghana",
      "iso": "GHA",
      "year": 2024,
      "generationTwh": 24.3,
      "mix": {
        "coal": 0.0,
        "gas": 61.5,
        "oil": 2.3,
        "nuclear": 0.0,
        "hydro": 35.4,
        "wind": 0.0,
        "solar": 0.7,
        "biofuel": 0.1,
        "otherRenewables": 0.0
      },
      "region": "Africa",
      "subregion": "Western Africa",
      "lat": 8.0,
      "lng": -2.0,
      "restName": "Ghana"
    },
    {
      "name": "Greece",
      "iso": "GRC",
      "year": 2025,
      "generationTwh": 58.3,
      "mix": {
        "coal": 4.7,
        "gas": 38.4,
        "oil": 7.2,
        "nuclear": 0.0,
        "hydro": 5.9,
        "wind": 20.4,
        "solar": 22.2,
        "biofuel": 1.2,
        "otherRenewables": 0.0
      },
      "region": "Europe",
      "subregion": "Southern Europe",
      "lat": 39.0,
      "lng": 22.0,
      "restName": "Greece"
    },
    {
      "name": "Guatemala",
      "iso": "GTM",
      "year": 2024,
      "generationTwh": 15.8,
      "mix": {
        "coal": 15.8,
        "gas": 0.0,
        "oil": 15.8,
        "nuclear": 0.0,
        "hydro": 39.9,
        "wind": 2.3,
        "solar": 1.8,
        "biofuel": 22.2,
        "otherRenewables": 2.2
      },
      "region": "Americas",
      "subregion": "Central America",
      "lat": 15.5,
      "lng": -90.25,
      "restName": "Guatemala"
    },
    {
      "name": "Guinea",
      "iso": "GIN",
      "year": 2024,
      "generationTwh": 4.0,
      "mix": {
        "coal": 0.0,
        "gas": 0.0,
        "oil": 24.8,
        "nuclear": 0.0,
        "hydro": 74.5,
        "wind": 0.0,
        "solar": 0.7,
        "biofuel": 0.0,
        "otherRenewables": 0.0
      },
      "region": "Africa",
      "subregion": "Western Africa",
      "lat": 11.0,
      "lng": -10.0,
      "restName": "Guinea"
    },
    {
      "name": "Honduras",
      "iso": "HND",
      "year": 2024,
      "generationTwh": 12.5,
      "mix": {
        "coal": 0.5,
        "gas": 0.0,
        "oil": 44.1,
        "nuclear": 0.0,
        "hydro": 30.4,
        "wind": 6.0,
        "solar": 9.5,
        "biofuel": 6.7,
        "otherRenewables": 2.8
      },
      "region": "Americas",
      "subregion": "Central America",
      "lat": 15.0,
      "lng": -86.5,
      "restName": "Honduras"
    },
    {
      "name": "Hong Kong",
      "iso": "HKG",
      "year": 2024,
      "generationTwh": 37.4,
      "mix": {
        "coal": 33.7,
        "gas": 64.1,
        "oil": 1.2,
        "nuclear": 0.0,
        "hydro": 0.0,
        "wind": 0.0,
        "solar": 0.6,
        "biofuel": 0.4,
        "otherRenewables": 0.0
      },
      "region": "Asia",
      "subregion": "Eastern Asia",
      "lat": 22.267,
      "lng": 114.188,
      "restName": "Hong Kong"
    },
    {
      "name": "Hungary",
      "iso": "HUN",
      "year": 2025,
      "generationTwh": 40.2,
      "mix": {
        "coal": 3.4,
        "gas": 20.3,
        "oil": 1.0,
        "nuclear": 40.0,
        "hydro": 0.6,
        "wind": 1.5,
        "solar": 27.3,
        "biofuel": 5.9,
        "otherRenewables": 0.0
      },
      "region": "Europe",
      "subregion": "Central Europe",
      "lat": 47.0,
      "lng": 20.0,
      "restName": "Hungary"
    },
    {
      "name": "Iceland",
      "iso": "ISL",
      "year": 2024,
      "generationTwh": 19.1,
      "mix": {
        "coal": 0.0,
        "gas": 0.0,
        "oil": 0.0,
        "nuclear": 0.0,
        "hydro": 70.6,
        "wind": 0.1,
        "solar": 0.1,
        "biofuel": 0.0,
        "otherRenewables": 29.2
      },
      "region": "Europe",
      "subregion": "Northern Europe",
      "lat": 65.0,
      "lng": -18.0,
      "restName": "Iceland"
    },
    {
      "name": "India",
      "iso": "IND",
      "year": 2025,
      "generationTwh": 2081.6,
      "mix": {
        "coal": 70.8,
        "gas": 2.3,
        "oil": 0.2,
        "nuclear": 2.6,
        "hydro": 8.6,
        "wind": 5.0,
        "solar": 9.4,
        "biofuel": 1.1,
        "otherRenewables": 0.0
      },
      "region": "Asia",
      "subregion": "Southern Asia",
      "lat": 20.0,
      "lng": 77.0,
      "restName": "India"
    },
    {
      "name": "Indonesia",
      "iso": "IDN",
      "year": 2024,
      "generationTwh": 371.5,
      "mix": {
        "coal": 61.6,
        "gas": 18.5,
        "oil": 1.9,
        "nuclear": 0.0,
        "hydro": 7.3,
        "wind": 0.1,
        "solar": 0.4,
        "biofuel": 5.7,
        "otherRenewables": 4.5
      },
      "region": "Asia",
      "subregion": "South-Eastern Asia",
      "lat": -5.0,
      "lng": 120.0,
      "restName": "Indonesia"
    },
    {
      "name": "Iran",
      "iso": "IRN",
      "year": 2025,
      "generationTwh": 395.8,
      "mix": {
        "coal": 0.2,
        "gas": 89.5,
        "oil": 4.6,
        "nuclear": 1.9,
        "hydro": 3.3,
        "wind": 0.3,
        "solar": 0.2,
        "biofuel": 0.0,
        "otherRenewables": 0.0
      },
      "region": "Asia",
      "subregion": "Southern Asia",
      "lat": 32.0,
      "lng": 53.0,
      "restName": "Iran"
    },
    {
      "name": "Iraq",
      "iso": "IRQ",
      "year": 2024,
      "generationTwh": 149.7,
      "mix": {
        "coal": 0.0,
        "gas": 53.0,
        "oil": 45.4,
        "nuclear": 0.0,
        "hydro": 1.3,
        "wind": 0.0,
        "solar": 0.3,
        "biofuel": 0.0,
        "otherRenewables": 0.0
      },
      "region": "Asia",
      "subregion": "Western Asia",
      "lat": 33.0,
      "lng": 44.0,
      "restName": "Iraq"
    },
    {
      "name": "Ireland",
      "iso": "IRL",
      "year": 2025,
      "generationTwh": 30.9,
      "mix": {
        "coal": 0.5,
        "gas": 48.4,
        "oil": 3.0,
        "nuclear": 0.0,
        "hydro": 2.1,
        "wind": 38.0,
        "solar": 4.7,
        "biofuel": 3.3,
        "otherRenewables": 0.0
      },
      "region": "Europe",
      "subregion": "Northern Europe",
      "lat": 53.0,
      "lng": -8.0,
      "restName": "Ireland"
    },
    {
      "name": "Israel",
      "iso": "ISR",
      "year": 2025,
      "generationTwh": 82.1,
      "mix": {
        "coal": 3.4,
        "gas": 79.6,
        "oil": 0.0,
        "nuclear": 0.0,
        "hydro": 0.0,
        "wind": 0.6,
        "solar": 16.2,
        "biofuel": 0.2,
        "otherRenewables": 0.0
      },
      "region": "Asia",
      "subregion": "Western Asia",
      "lat": 31.47,
      "lng": 35.13,
      "restName": "Israel"
    },
    {
      "name": "Italy",
      "iso": "ITA",
      "year": 2025,
      "generationTwh": 264.7,
      "mix": {
        "coal": 1.4,
        "gas": 47.2,
        "oil": 2.6,
        "nuclear": 0.0,
        "hydro": 15.8,
        "wind": 8.1,
        "solar": 16.9,
        "biofuel": 5.9,
        "otherRenewables": 2.1
      },
      "region": "Europe",
      "subregion": "Southern Europe",
      "lat": 42.83333333,
      "lng": 12.83333333,
      "restName": "Italy"
    },
    {
      "name": "Jamaica",
      "iso": "JAM",
      "year": 2024,
      "generationTwh": 4.9,
      "mix": {
        "coal": 0.0,
        "gas": 57.0,
        "oil": 30.5,
        "nuclear": 0.0,
        "hydro": 2.4,
        "wind": 5.9,
        "solar": 3.0,
        "biofuel": 1.2,
        "otherRenewables": 0.0
      },
      "region": "Americas",
      "subregion": "Caribbean",
      "lat": 18.25,
      "lng": -77.5,
      "restName": "Jamaica"
    },
    {
      "name": "Japan",
      "iso": "JPN",
      "year": 2025,
      "generationTwh": 1029.9,
      "mix": {
        "coal": 32.1,
        "gas": 32.8,
        "oil": 2.5,
        "nuclear": 9.1,
        "hydro": 7.2,
        "wind": 1.2,
        "solar": 9.8,
        "biofuel": 5.3,
        "otherRenewables": 0.0
      },
      "region": "Asia",
      "subregion": "Eastern Asia",
      "lat": 36.0,
      "lng": 138.0,
      "restName": "Japan"
    },
    {
      "name": "Jordan",
      "iso": "JOR",
      "year": 2024,
      "generationTwh": 23.7,
      "mix": {
        "coal": 0.0,
        "gas": 62.0,
        "oil": 13.9,
        "nuclear": 0.0,
        "hydro": 0.1,
        "wind": 7.4,
        "solar": 16.6,
        "biofuel": 0.0,
        "otherRenewables": 0.0
      },
      "region": "Asia",
      "subregion": "Western Asia",
      "lat": 31.0,
      "lng": 36.0,
      "restName": "Jordan"
    },
    {
      "name": "Kazakhstan",
      "iso": "KAZ",
      "year": 2025,
      "generationTwh": 123.7,
      "mix": {
        "coal": 54.3,
        "gas": 29.4,
        "oil": 1.5,
        "nuclear": 0.0,
        "hydro": 8.5,
        "wind": 4.7,
        "solar": 1.6,
        "biofuel": 0.0,
        "otherRenewables": 0.0
      },
      "region": "Asia",
      "subregion": "Central Asia",
      "lat": 48.0,
      "lng": 68.0,
      "restName": "Kazakhstan"
    },
    {
      "name": "Kenya",
      "iso": "KEN",
      "year": 2025,
      "generationTwh": 14.0,
      "mix": {
        "coal": 0.0,
        "gas": 0.0,
        "oil": 10.0,
        "nuclear": 0.0,
        "hydro": 20.9,
        "wind": 16.4,
        "solar": 4.6,
        "biofuel": 2.1,
        "otherRenewables": 46.0
      },
      "region": "Africa",
      "subregion": "Eastern Africa",
      "lat": 1.0,
      "lng": 38.0,
      "restName": "Kenya"
    },
    {
      "name": "Kuwait",
      "iso": "KWT",
      "year": 2025,
      "generationTwh": 92.5,
      "mix": {
        "coal": 0.0,
        "gas": 62.0,
        "oil": 35.8,
        "nuclear": 0.0,
        "hydro": 0.0,
        "wind": 2.0,
        "solar": 0.2,
        "biofuel": 0.0,
        "otherRenewables": 0.0
      },
      "region": "Asia",
      "subregion": "Western Asia",
      "lat": 29.5,
      "lng": 45.75,
      "restName": "Kuwait"
    },
    {
      "name": "Kyrgyzstan",
      "iso": "KGZ",
      "year": 2025,
      "generationTwh": 15.8,
      "mix": {
        "coal": 12.6,
        "gas": 1.7,
        "oil": 1.0,
        "nuclear": 0.0,
        "hydro": 84.7,
        "wind": 0.0,
        "solar": 0.0,
        "biofuel": 0.0,
        "otherRenewables": 0.0
      },
      "region": "Asia",
      "subregion": "Central Asia",
      "lat": 41.0,
      "lng": 75.0,
      "restName": "Kyrgyzstan"
    },
    {
      "name": "Laos",
      "iso": "LAO",
      "year": 2024,
      "generationTwh": 52.3,
      "mix": {
        "coal": 23.3,
        "gas": 0.0,
        "oil": 0.0,
        "nuclear": 0.0,
        "hydro": 76.4,
        "wind": 0.0,
        "solar": 0.2,
        "biofuel": 0.1,
        "otherRenewables": 0.0
      },
      "region": "Asia",
      "subregion": "South-Eastern Asia",
      "lat": 18.0,
      "lng": 105.0,
      "restName": "Laos"
    },
    {
      "name": "Latvia",
      "iso": "LVA",
      "year": 2025,
      "generationTwh": 6.3,
      "mix": {
        "coal": 0.0,
        "gas": 26.2,
        "oil": 0.8,
        "nuclear": 0.0,
        "hydro": 46.7,
        "wind": 3.5,
        "solar": 13.1,
        "biofuel": 9.7,
        "otherRenewables": 0.0
      },
      "region": "Europe",
      "subregion": "Northern Europe",
      "lat": 57.0,
      "lng": 25.0,
      "restName": "Latvia"
    },
    {
      "name": "Lebanon",
      "iso": "LBN",
      "year": 2024,
      "generationTwh": 5.3,
      "mix": {
        "coal": 0.0,
        "gas": 0.0,
        "oil": 56.1,
        "nuclear": 0.0,
        "hydro": 13.1,
        "wind": 0.2,
        "solar": 30.0,
        "biofuel": 0.6,
        "otherRenewables": 0.0
      },
      "region": "Asia",
      "subregion": "Western Asia",
      "lat": 33.83333333,
      "lng": 35.83333333,
      "restName": "Lebanon"
    },
    {
      "name": "Libya",
      "iso": "LBY",
      "year": 2024,
      "generationTwh": 34.6,
      "mix": {
        "coal": 0.0,
        "gas": 74.6,
        "oil": 25.4,
        "nuclear": 0.0,
        "hydro": 0.0,
        "wind": 0.0,
        "solar": 0.0,
        "biofuel": 0.0,
        "otherRenewables": 0.0
      },
      "region": "Africa",
      "subregion": "Northern Africa",
      "lat": 25.0,
      "lng": 17.0,
      "restName": "Libya"
    },
    {
      "name": "Lithuania",
      "iso": "LTU",
      "year": 2025,
      "generationTwh": 8.9,
      "mix": {
        "coal": 0.0,
        "gas": 16.5,
        "oil": 5.8,
        "nuclear": 0.0,
        "hydro": 3.9,
        "wind": 45.0,
        "solar": 18.8,
        "biofuel": 10.0,
        "otherRenewables": 0.0
      },
      "region": "Europe",
      "subregion": "Northern Europe",
      "lat": 56.0,
      "lng": 24.0,
      "restName": "Lithuania"
    },
    {
      "name": "Luxembourg",
      "iso": "LUX",
      "year": 2012,
      "generationTwh": 2.8,
      "mix": {
        "coal": 0.0,
        "gas": 86.6,
        "oil": 2.2,
        "nuclear": 0.0,
        "hydro": 3.6,
        "wind": 2.9,
        "solar": 1.4,
        "biofuel": 3.3,
        "otherRenewables": 0.0
      },
      "region": "Europe",
      "subregion": "Western Europe",
      "lat": 49.75,
      "lng": 6.16666666,
      "restName": "Luxembourg"
    },
    {
      "name": "Macao",
      "iso": "MAC",
      "year": 2005,
      "generationTwh": 2.0,
      "mix": {
        "coal": 0.0,
        "gas": 0.0,
        "oil": 92.1,
        "nuclear": 0.0,
        "hydro": 0.0,
        "wind": 0.0,
        "solar": 0.0,
        "biofuel": 7.9,
        "otherRenewables": 0.0
      },
      "region": "Asia",
      "subregion": "Eastern Asia",
      "lat": 22.16666666,
      "lng": 113.55,
      "restName": "Macau"
    },
    {
      "name": "Madagascar",
      "iso": "MDG",
      "year": 2024,
      "generationTwh": 2.4,
      "mix": {
        "coal": 20.6,
        "gas": 0.0,
        "oil": 37.1,
        "nuclear": 0.0,
        "hydro": 37.0,
        "wind": 0.0,
        "solar": 4.1,
        "biofuel": 1.2,
        "otherRenewables": 0.0
      },
      "region": "Africa",
      "subregion": "Eastern Africa",
      "lat": -20.0,
      "lng": 47.0,
      "restName": "Madagascar"
    },
    {
      "name": "Malawi",
      "iso": "MWI",
      "year": 2016,
      "generationTwh": 2.1,
      "mix": {
        "coal": 0.0,
        "gas": 0.0,
        "oil": 6.0,
        "nuclear": 0.0,
        "hydro": 90.3,
        "wind": 0.0,
        "solar": 1.4,
        "biofuel": 2.3,
        "otherRenewables": 0.0
      },
      "region": "Africa",
      "subregion": "Eastern Africa",
      "lat": -13.5,
      "lng": 34.0,
      "restName": "Malawi"
    },
    {
      "name": "Malaysia",
      "iso": "MYS",
      "year": 2025,
      "generationTwh": 201.1,
      "mix": {
        "coal": 44.6,
        "gas": 33.8,
        "oil": 1.0,
        "nuclear": 0.0,
        "hydro": 17.5,
        "wind": 0.0,
        "solar": 2.2,
        "biofuel": 0.9,
        "otherRenewables": 0.0
      },
      "region": "Asia",
      "subregion": "South-Eastern Asia",
      "lat": 2.5,
      "lng": 112.5,
      "restName": "Malaysia"
    },
    {
      "name": "Mali",
      "iso": "MLI",
      "year": 2024,
      "generationTwh": 6.0,
      "mix": {
        "coal": 0.0,
        "gas": 0.0,
        "oil": 80.5,
        "nuclear": 0.0,
        "hydro": 15.4,
        "wind": 0.0,
        "solar": 2.9,
        "biofuel": 1.2,
        "otherRenewables": 0.0
      },
      "region": "Africa",
      "subregion": "Western Africa",
      "lat": 17.0,
      "lng": -4.0,
      "restName": "Mali"
    },
    {
      "name": "Malta",
      "iso": "MLT",
      "year": 2025,
      "generationTwh": 2.2,
      "mix": {
        "coal": 0.0,
        "gas": 83.1,
        "oil": 0.9,
        "nuclear": 0.0,
        "hydro": 0.0,
        "wind": 0.0,
        "solar": 15.5,
        "biofuel": 0.5,
        "otherRenewables": 0.0
      },
      "region": "Europe",
      "subregion": "Southern Europe",
      "lat": 35.83333333,
      "lng": 14.58333333,
      "restName": "Malta"
    },
    {
      "name": "Mauritania",
      "iso": "MRT",
      "year": 2024,
      "generationTwh": 2.1,
      "mix": {
        "coal": 0.0,
        "gas": 0.0,
        "oil": 77.4,
        "nuclear": 0.0,
        "hydro": 10.1,
        "wind": 4.8,
        "solar": 7.7,
        "biofuel": 0.0,
        "otherRenewables": 0.0
      },
      "region": "Africa",
      "subregion": "Western Africa",
      "lat": 20.0,
      "lng": -12.0,
      "restName": "Mauritania"
    },
    {
      "name": "Mauritius",
      "iso": "MUS",
      "year": 2024,
      "generationTwh": 3.4,
      "mix": {
        "coal": 39.3,
        "gas": 0.0,
        "oil": 42.8,
        "nuclear": 0.0,
        "hydro": 3.2,
        "wind": 0.3,
        "solar": 5.0,
        "biofuel": 9.4,
        "otherRenewables": 0.0
      },
      "region": "Africa",
      "subregion": "Eastern Africa",
      "lat": -20.28333333,
      "lng": 57.55,
      "restName": "Mauritius"
    },
    {
      "name": "Mexico",
      "iso": "MEX",
      "year": 2025,
      "generationTwh": 357.0,
      "mix": {
        "coal": 3.0,
        "gas": 61.6,
        "oil": 9.4,
        "nuclear": 2.8,
        "hydro": 8.1,
        "wind": 6.0,
        "solar": 7.4,
        "biofuel": 1.7,
        "otherRenewables": 0.0
      },
      "region": "Americas",
      "subregion": "North America",
      "lat": 23.0,
      "lng": -102.0,
      "restName": "Mexico"
    },
    {
      "name": "Moldova",
      "iso": "MDA",
      "year": 2025,
      "generationTwh": 6.2,
      "mix": {
        "coal": 0.0,
        "gas": 85.2,
        "oil": 3.6,
        "nuclear": 0.0,
        "hydro": 5.7,
        "wind": 2.6,
        "solar": 2.6,
        "biofuel": 0.3,
        "otherRenewables": 0.0
      },
      "region": "Europe",
      "subregion": "Eastern Europe",
      "lat": 47.0,
      "lng": 29.0,
      "restName": "Moldova"
    },
    {
      "name": "Mongolia",
      "iso": "MNG",
      "year": 2025,
      "generationTwh": 9.7,
      "mix": {
        "coal": 85.7,
        "gas": 0.0,
        "oil": 5.9,
        "nuclear": 0.0,
        "hydro": 0.6,
        "wind": 5.6,
        "solar": 2.2,
        "biofuel": 0.0,
        "otherRenewables": 0.0
      },
      "region": "Asia",
      "subregion": "Eastern Asia",
      "lat": 46.0,
      "lng": 105.0,
      "restName": "Mongolia"
    },
    {
      "name": "Montenegro",
      "iso": "MNE",
      "year": 2025,
      "generationTwh": 2.5,
      "mix": {
        "coal": 24.4,
        "gas": 0.0,
        "oil": 0.0,
        "nuclear": 0.0,
        "hydro": 58.5,
        "wind": 11.4,
        "solar": 5.7,
        "biofuel": 0.0,
        "otherRenewables": 0.0
      },
      "region": "Europe",
      "subregion": "Southeast Europe",
      "lat": 42.5,
      "lng": 19.3,
      "restName": "Montenegro"
    },
    {
      "name": "Morocco",
      "iso": "MAR",
      "year": 2025,
      "generationTwh": 44.5,
      "mix": {
        "coal": 61.6,
        "gas": 10.9,
        "oil": 3.6,
        "nuclear": 0.0,
        "hydro": 2.0,
        "wind": 16.0,
        "solar": 5.8,
        "biofuel": 0.1,
        "otherRenewables": 0.0
      },
      "region": "Africa",
      "subregion": "Northern Africa",
      "lat": 32.0,
      "lng": -5.0,
      "restName": "Morocco"
    },
    {
      "name": "Mozambique",
      "iso": "MOZ",
      "year": 2024,
      "generationTwh": 19.8,
      "mix": {
        "coal": 0.0,
        "gas": 15.8,
        "oil": 0.8,
        "nuclear": 0.0,
        "hydro": 82.3,
        "wind": 0.0,
        "solar": 0.4,
        "biofuel": 0.7,
        "otherRenewables": 0.0
      },
      "region": "Africa",
      "subregion": "Eastern Africa",
      "lat": -18.25,
      "lng": 35.0,
      "restName": "Mozambique"
    },
    {
      "name": "Myanmar",
      "iso": "MMR",
      "year": 2024,
      "generationTwh": 21.7,
      "mix": {
        "coal": 5.5,
        "gas": 46.0,
        "oil": 0.6,
        "nuclear": 0.0,
        "hydro": 46.1,
        "wind": 0.0,
        "solar": 0.6,
        "biofuel": 1.2,
        "otherRenewables": 0.0
      },
      "region": "Asia",
      "subregion": "South-Eastern Asia",
      "lat": 22.0,
      "lng": 98.0,
      "restName": "Myanmar"
    },
    {
      "name": "Namibia",
      "iso": "NAM",
      "year": 2020,
      "generationTwh": 2.0,
      "mix": {
        "coal": 3.0,
        "gas": 0.0,
        "oil": 0.5,
        "nuclear": 0.0,
        "hydro": 75.0,
        "wind": 1.0,
        "solar": 20.5,
        "biofuel": 0.0,
        "otherRenewables": 0.0
      },
      "region": "Africa",
      "subregion": "Southern Africa",
      "lat": -22.0,
      "lng": 17.0,
      "restName": "Namibia"
    },
    {
      "name": "Nepal",
      "iso": "NPL",
      "year": 2024,
      "generationTwh": 11.1,
      "mix": {
        "coal": 0.0,
        "gas": 0.0,
        "oil": 0.0,
        "nuclear": 0.0,
        "hydro": 98.8,
        "wind": 0.1,
        "solar": 1.1,
        "biofuel": 0.0,
        "otherRenewables": 0.0
      },
      "region": "Asia",
      "subregion": "Southern Asia",
      "lat": 28.0,
      "lng": 84.0,
      "restName": "Nepal"
    },
    {
      "name": "Netherlands",
      "iso": "NLD",
      "year": 2025,
      "generationTwh": 135.0,
      "mix": {
        "coal": 7.1,
        "gas": 34.8,
        "oil": 3.9,
        "nuclear": 3.0,
        "hydro": 0.0,
        "wind": 25.0,
        "solar": 21.1,
        "biofuel": 5.1,
        "otherRenewables": 0.0
      },
      "region": "Europe",
      "subregion": "Western Europe",
      "lat": 52.5,
      "lng": 5.75,
      "restName": "Netherlands"
    },
    {
      "name": "New Caledonia",
      "iso": "NCL",
      "year": 2024,
      "generationTwh": 3.1,
      "mix": {
        "coal": 36.6,
        "gas": 0.0,
        "oil": 36.5,
        "nuclear": 0.0,
        "hydro": 17.3,
        "wind": 1.3,
        "solar": 8.3,
        "biofuel": 0.0,
        "otherRenewables": 0.0
      },
      "region": "Oceania",
      "subregion": "Melanesia",
      "lat": -21.5,
      "lng": 165.5,
      "restName": "New Caledonia"
    },
    {
      "name": "New Zealand",
      "iso": "NZL",
      "year": 2025,
      "generationTwh": 43.3,
      "mix": {
        "coal": 1.1,
        "gas": 8.9,
        "oil": 1.5,
        "nuclear": 0.0,
        "hydro": 54.8,
        "wind": 9.7,
        "solar": 0.9,
        "biofuel": 1.3,
        "otherRenewables": 21.8
      },
      "region": "Oceania",
      "subregion": "Australia and New Zealand",
      "lat": -41.0,
      "lng": 174.0,
      "restName": "New Zealand"
    },
    {
      "name": "Nicaragua",
      "iso": "NIC",
      "year": 2024,
      "generationTwh": 4.5,
      "mix": {
        "coal": 0.0,
        "gas": 0.0,
        "oil": 37.5,
        "nuclear": 0.0,
        "hydro": 14.4,
        "wind": 12.4,
        "solar": 0.7,
        "biofuel": 19.7,
        "otherRenewables": 15.3
      },
      "region": "Americas",
      "subregion": "Central America",
      "lat": 13.0,
      "lng": -85.0,
      "restName": "Nicaragua"
    },
    {
      "name": "Nigeria",
      "iso": "NGA",
      "year": 2025,
      "generationTwh": 41.5,
      "mix": {
        "coal": 0.0,
        "gas": 68.7,
        "oil": 0.0,
        "nuclear": 0.0,
        "hydro": 30.9,
        "wind": 0.0,
        "solar": 0.3,
        "biofuel": 0.1,
        "otherRenewables": 0.0
      },
      "region": "Africa",
      "subregion": "Western Africa",
      "lat": 10.0,
      "lng": 8.0,
      "restName": "Nigeria"
    },
    {
      "name": "North Korea",
      "iso": "PRK",
      "year": 2024,
      "generationTwh": 27.1,
      "mix": {
        "coal": 34.1,
        "gas": 0.0,
        "oil": 2.6,
        "nuclear": 0.0,
        "hydro": 62.7,
        "wind": 0.0,
        "solar": 0.6,
        "biofuel": 0.0,
        "otherRenewables": 0.0
      },
      "region": "Asia",
      "subregion": "Eastern Asia",
      "lat": 40.0,
      "lng": 127.0,
      "restName": "North Korea"
    },
    {
      "name": "North Macedonia",
      "iso": "MKD",
      "year": 2025,
      "generationTwh": 6.8,
      "mix": {
        "coal": 30.7,
        "gas": 19.6,
        "oil": 2.5,
        "nuclear": 0.0,
        "hydro": 19.9,
        "wind": 2.9,
        "solar": 23.8,
        "biofuel": 0.6,
        "otherRenewables": 0.0
      },
      "region": "Europe",
      "subregion": "Southeast Europe",
      "lat": 41.83333333,
      "lng": 22.0,
      "restName": "North Macedonia"
    },
    {
      "name": "Norway",
      "iso": "NOR",
      "year": 2025,
      "generationTwh": 160.8,
      "mix": {
        "coal": 0.0,
        "gas": 0.6,
        "oil": 0.4,
        "nuclear": 0.0,
        "hydro": 90.1,
        "wind": 8.4,
        "solar": 0.3,
        "biofuel": 0.1,
        "otherRenewables": 0.1
      },
      "region": "Europe",
      "subregion": "Northern Europe",
      "lat": 62.0,
      "lng": 10.0,
      "restName": "Norway"
    },
    {
      "name": "Oman",
      "iso": "OMN",
      "year": 2025,
      "generationTwh": 52.8,
      "mix": {
        "coal": 0.0,
        "gas": 91.8,
        "oil": 3.6,
        "nuclear": 0.0,
        "hydro": 0.0,
        "wind": 0.2,
        "solar": 4.4,
        "biofuel": 0.0,
        "otherRenewables": 0.0
      },
      "region": "Asia",
      "subregion": "Western Asia",
      "lat": 21.0,
      "lng": 57.0,
      "restName": "Oman"
    },
    {
      "name": "Pakistan",
      "iso": "PAK",
      "year": 2025,
      "generationTwh": 195.0,
      "mix": {
        "coal": 14.8,
        "gas": 21.0,
        "oil": 9.2,
        "nuclear": 12.2,
        "hydro": 20.2,
        "wind": 2.9,
        "solar": 18.8,
        "biofuel": 0.9,
        "otherRenewables": 0.0
      },
      "region": "Asia",
      "subregion": "Southern Asia",
      "lat": 30.0,
      "lng": 70.0,
      "restName": "Pakistan"
    },
    {
      "name": "Panama",
      "iso": "PAN",
      "year": 2024,
      "generationTwh": 13.4,
      "mix": {
        "coal": 3.7,
        "gas": 20.8,
        "oil": 7.4,
        "nuclear": 0.0,
        "hydro": 53.2,
        "wind": 7.1,
        "solar": 7.4,
        "biofuel": 0.4,
        "otherRenewables": 0.0
      },
      "region": "Americas",
      "subregion": "Central America",
      "lat": 9.0,
      "lng": -80.0,
      "restName": "Panama"
    },
    {
      "name": "Papua New Guinea",
      "iso": "PNG",
      "year": 2024,
      "generationTwh": 4.7,
      "mix": {
        "coal": 0.0,
        "gas": 19.2,
        "oil": 57.2,
        "nuclear": 0.0,
        "hydro": 21.1,
        "wind": 0.0,
        "solar": 0.2,
        "biofuel": 0.2,
        "otherRenewables": 2.1
      },
      "region": "Oceania",
      "subregion": "Melanesia",
      "lat": -6.0,
      "lng": 147.0,
      "restName": "Papua New Guinea"
    },
    {
      "name": "Paraguay",
      "iso": "PRY",
      "year": 2025,
      "generationTwh": 45.4,
      "mix": {
        "coal": 0.0,
        "gas": 0.0,
        "oil": 0.0,
        "nuclear": 0.0,
        "hydro": 99.5,
        "wind": 0.0,
        "solar": 0.0,
        "biofuel": 0.5,
        "otherRenewables": 0.0
      },
      "region": "Americas",
      "subregion": "South America",
      "lat": -23.0,
      "lng": -58.0,
      "restName": "Paraguay"
    },
    {
      "name": "Peru",
      "iso": "PER",
      "year": 2025,
      "generationTwh": 60.4,
      "mix": {
        "coal": 0.0,
        "gas": 36.1,
        "oil": 0.2,
        "nuclear": 0.0,
        "hydro": 56.1,
        "wind": 3.5,
        "solar": 3.0,
        "biofuel": 1.1,
        "otherRenewables": 0.0
      },
      "region": "Americas",
      "subregion": "South America",
      "lat": -10.0,
      "lng": -76.0,
      "restName": "Peru"
    },
    {
      "name": "Philippines",
      "iso": "PHL",
      "year": 2025,
      "generationTwh": 123.1,
      "mix": {
        "coal": 58.6,
        "gas": 17.3,
        "oil": 0.8,
        "nuclear": 0.0,
        "hydro": 10.3,
        "wind": 1.2,
        "solar": 2.4,
        "biofuel": 1.2,
        "otherRenewables": 8.2
      },
      "region": "Asia",
      "subregion": "South-Eastern Asia",
      "lat": 13.0,
      "lng": 122.0,
      "restName": "Philippines"
    },
    {
      "name": "Poland",
      "iso": "POL",
      "year": 2025,
      "generationTwh": 173.3,
      "mix": {
        "coal": 50.4,
        "gas": 14.3,
        "oil": 3.8,
        "nuclear": 0.0,
        "hydro": 1.0,
        "wind": 14.2,
        "solar": 11.3,
        "biofuel": 4.9,
        "otherRenewables": 0.1
      },
      "region": "Europe",
      "subregion": "Central Europe",
      "lat": 52.0,
      "lng": 20.0,
      "restName": "Poland"
    },
    {
      "name": "Portugal",
      "iso": "PRT",
      "year": 2025,
      "generationTwh": 51.1,
      "mix": {
        "coal": 0.0,
        "gas": 16.4,
        "oil": 2.6,
        "nuclear": 0.0,
        "hydro": 29.8,
        "wind": 26.7,
        "solar": 17.3,
        "biofuel": 6.8,
        "otherRenewables": 0.4
      },
      "region": "Europe",
      "subregion": "Southern Europe",
      "lat": 39.5,
      "lng": -8.0,
      "restName": "Portugal"
    },
    {
      "name": "Puerto Rico",
      "iso": "PRI",
      "year": 2025,
      "generationTwh": 20.3,
      "mix": {
        "coal": 16.5,
        "gas": 29.5,
        "oil": 47.8,
        "nuclear": 0.0,
        "hydro": 0.2,
        "wind": 1.1,
        "solar": 4.9,
        "biofuel": 0.0,
        "otherRenewables": 0.0
      },
      "region": "Americas",
      "subregion": "Caribbean",
      "lat": 18.25,
      "lng": -66.5,
      "restName": "Puerto Rico"
    },
    {
      "name": "Qatar",
      "iso": "QAT",
      "year": 2025,
      "generationTwh": 56.2,
      "mix": {
        "coal": 0.0,
        "gas": 96.0,
        "oil": 0.0,
        "nuclear": 0.0,
        "hydro": 0.0,
        "wind": 0.0,
        "solar": 3.8,
        "biofuel": 0.2,
        "otherRenewables": 0.0
      },
      "region": "Asia",
      "subregion": "Western Asia",
      "lat": 25.5,
      "lng": 51.25,
      "restName": "Qatar"
    },
    {
      "name": "Reunion",
      "iso": "REU",
      "year": 2023,
      "generationTwh": 3.1,
      "mix": {
        "coal": 13.0,
        "gas": 0.0,
        "oil": 30.3,
        "nuclear": 0.0,
        "hydro": 12.7,
        "wind": 0.7,
        "solar": 9.4,
        "biofuel": 33.9,
        "otherRenewables": 0.0
      },
      "region": "Africa",
      "subregion": "Eastern Africa",
      "lat": -21.15,
      "lng": 55.5,
      "restName": "Réunion"
    },
    {
      "name": "Romania",
      "iso": "ROU",
      "year": 2025,
      "generationTwh": 49.8,
      "mix": {
        "coal": 13.4,
        "gas": 18.7,
        "oil": 0.4,
        "nuclear": 20.5,
        "hydro": 24.2,
        "wind": 12.0,
        "solar": 9.8,
        "biofuel": 1.0,
        "otherRenewables": 0.0
      },
      "region": "Europe",
      "subregion": "Southeast Europe",
      "lat": 46.0,
      "lng": 25.0,
      "restName": "Romania"
    },
    {
      "name": "Russia",
      "iso": "RUS",
      "year": 2025,
      "generationTwh": 1192.8,
      "mix": {
        "coal": 18.4,
        "gas": 44.8,
        "oil": 1.2,
        "nuclear": 18.3,
        "hydro": 16.7,
        "wind": 0.3,
        "solar": 0.2,
        "biofuel": 0.1,
        "otherRenewables": 0.0
      },
      "region": "Europe",
      "subregion": "Eastern Europe",
      "lat": 60.0,
      "lng": 100.0,
      "restName": "Russia"
    },
    {
      "name": "Saudi Arabia",
      "iso": "SAU",
      "year": 2024,
      "generationTwh": 454.6,
      "mix": {
        "coal": 0.0,
        "gas": 63.4,
        "oil": 34.5,
        "nuclear": 0.0,
        "hydro": 0.0,
        "wind": 0.3,
        "solar": 1.8,
        "biofuel": 0.0,
        "otherRenewables": 0.0
      },
      "region": "Asia",
      "subregion": "Western Asia",
      "lat": 25.0,
      "lng": 45.0,
      "restName": "Saudi Arabia"
    },
    {
      "name": "Senegal",
      "iso": "SEN",
      "year": 2024,
      "generationTwh": 7.6,
      "mix": {
        "coal": 1.3,
        "gas": 0.3,
        "oil": 78.6,
        "nuclear": 0.0,
        "hydro": 4.1,
        "wind": 5.4,
        "solar": 8.9,
        "biofuel": 1.4,
        "otherRenewables": 0.0
      },
      "region": "Africa",
      "subregion": "Western Africa",
      "lat": 14.0,
      "lng": -14.0,
      "restName": "Senegal"
    },
    {
      "name": "Serbia",
      "iso": "SRB",
      "year": 2025,
      "generationTwh": 36.6,
      "mix": {
        "coal": 65.1,
        "gas": 6.9,
        "oil": 0.3,
        "nuclear": 0.0,
        "hydro": 22.2,
        "wind": 4.0,
        "solar": 0.4,
        "biofuel": 1.1,
        "otherRenewables": 0.0
      },
      "region": "Europe",
      "subregion": "Southeast Europe",
      "lat": 44.0,
      "lng": 21.0,
      "restName": "Serbia"
    },
    {
      "name": "Singapore",
      "iso": "SGP",
      "year": 2025,
      "generationTwh": 60.1,
      "mix": {
        "coal": 0.9,
        "gas": 91.2,
        "oil": 2.4,
        "nuclear": 0.0,
        "hydro": 0.0,
        "wind": 0.0,
        "solar": 2.7,
        "biofuel": 2.8,
        "otherRenewables": 0.0
      },
      "region": "Asia",
      "subregion": "South-Eastern Asia",
      "lat": 1.36666666,
      "lng": 103.8,
      "restName": "Singapore"
    },
    {
      "name": "Slovakia",
      "iso": "SVK",
      "year": 2025,
      "generationTwh": 29.1,
      "mix": {
        "coal": 1.1,
        "gas": 11.3,
        "oil": 2.5,
        "nuclear": 66.4,
        "hydro": 10.9,
        "wind": 0.0,
        "solar": 2.4,
        "biofuel": 5.4,
        "otherRenewables": 0.0
      },
      "region": "Europe",
      "subregion": "Central Europe",
      "lat": 48.66666666,
      "lng": 19.5,
      "restName": "Slovakia"
    },
    {
      "name": "Slovenia",
      "iso": "SVN",
      "year": 2025,
      "generationTwh": 14.8,
      "mix": {
        "coal": 14.7,
        "gas": 6.4,
        "oil": 0.0,
        "nuclear": 39.2,
        "hydro": 27.2,
        "wind": 0.1,
        "solar": 10.4,
        "biofuel": 2.0,
        "otherRenewables": 0.0
      },
      "region": "Europe",
      "subregion": "Central Europe",
      "lat": 46.11666666,
      "lng": 14.81666666,
      "restName": "Slovenia"
    },
    {
      "name": "South Africa",
      "iso": "ZAF",
      "year": 2025,
      "generationTwh": 242.8,
      "mix": {
        "coal": 81.3,
        "gas": 0.0,
        "oil": 0.8,
        "nuclear": 4.2,
        "hydro": 0.8,
        "wind": 4.7,
        "solar": 8.0,
        "biofuel": 0.2,
        "otherRenewables": 0.0
      },
      "region": "Africa",
      "subregion": "Southern Africa",
      "lat": -29.0,
      "lng": 24.0,
      "restName": "South Africa"
    },
    {
      "name": "South Korea",
      "iso": "KOR",
      "year": 2025,
      "generationTwh": 624.7,
      "mix": {
        "coal": 31.0,
        "gas": 27.9,
        "oil": 1.0,
        "nuclear": 29.6,
        "hydro": 0.6,
        "wind": 0.6,
        "solar": 6.1,
        "biofuel": 3.2,
        "otherRenewables": 0.0
      },
      "region": "Asia",
      "subregion": "Eastern Asia",
      "lat": 37.0,
      "lng": 127.5,
      "restName": "South Korea"
    },
    {
      "name": "Spain",
      "iso": "ESP",
      "year": 2025,
      "generationTwh": 287.9,
      "mix": {
        "coal": 0.3,
        "gas": 21.6,
        "oil": 3.5,
        "nuclear": 18.8,
        "hydro": 11.4,
        "wind": 20.4,
        "solar": 21.8,
        "biofuel": 2.2,
        "otherRenewables": 0.0
      },
      "region": "Europe",
      "subregion": "Southern Europe",
      "lat": 40.0,
      "lng": -4.0,
      "restName": "Spain"
    },
    {
      "name": "Sri Lanka",
      "iso": "LKA",
      "year": 2025,
      "generationTwh": 17.2,
      "mix": {
        "coal": 27.5,
        "gas": 0.0,
        "oil": 10.8,
        "nuclear": 0.0,
        "hydro": 38.3,
        "wind": 5.4,
        "solar": 16.5,
        "biofuel": 1.3,
        "otherRenewables": 0.2
      },
      "region": "Asia",
      "subregion": "Southern Asia",
      "lat": 7.0,
      "lng": 81.0,
      "restName": "Sri Lanka"
    },
    {
      "name": "Sudan",
      "iso": "SDN",
      "year": 2024,
      "generationTwh": 14.8,
      "mix": {
        "coal": 0.0,
        "gas": 0.0,
        "oil": 20.3,
        "nuclear": 0.0,
        "hydro": 77.9,
        "wind": 0.0,
        "solar": 1.1,
        "biofuel": 0.7,
        "otherRenewables": 0.0
      },
      "region": "Africa",
      "subregion": "Northern Africa",
      "lat": 15.0,
      "lng": 30.0,
      "restName": "Sudan"
    },
    {
      "name": "Suriname",
      "iso": "SUR",
      "year": 2022,
      "generationTwh": 2.1,
      "mix": {
        "coal": 0.0,
        "gas": 0.9,
        "oil": 54.5,
        "nuclear": 0.0,
        "hydro": 43.6,
        "wind": 0.0,
        "solar": 0.5,
        "biofuel": 0.5,
        "otherRenewables": 0.0
      },
      "region": "Americas",
      "subregion": "South America",
      "lat": 4.0,
      "lng": -56.0,
      "restName": "Suriname"
    },
    {
      "name": "Sweden",
      "iso": "SWE",
      "year": 2025,
      "generationTwh": 170.7,
      "mix": {
        "coal": 0.0,
        "gas": 0.1,
        "oil": 1.2,
        "nuclear": 27.6,
        "hydro": 39.9,
        "wind": 22.8,
        "solar": 2.6,
        "biofuel": 5.8,
        "otherRenewables": 0.0
      },
      "region": "Europe",
      "subregion": "Northern Europe",
      "lat": 62.0,
      "lng": 15.0,
      "restName": "Sweden"
    },
    {
      "name": "Switzerland",
      "iso": "CHE",
      "year": 2025,
      "generationTwh": 65.0,
      "mix": {
        "coal": 0.0,
        "gas": 0.4,
        "oil": 1.9,
        "nuclear": 29.9,
        "hydro": 52.3,
        "wind": 0.2,
        "solar": 12.1,
        "biofuel": 1.6,
        "otherRenewables": 1.6
      },
      "region": "Europe",
      "subregion": "Western Europe",
      "lat": 47.0,
      "lng": 8.0,
      "restName": "Switzerland"
    },
    {
      "name": "Syria",
      "iso": "SYR",
      "year": 2024,
      "generationTwh": 24.9,
      "mix": {
        "coal": 0.0,
        "gas": 52.3,
        "oil": 44.2,
        "nuclear": 0.0,
        "hydro": 3.0,
        "wind": 0.0,
        "solar": 0.4,
        "biofuel": 0.1,
        "otherRenewables": 0.0
      },
      "region": "Asia",
      "subregion": "Western Asia",
      "lat": 35.0,
      "lng": 38.0,
      "restName": "Syria"
    },
    {
      "name": "Taiwan",
      "iso": "TWN",
      "year": 2025,
      "generationTwh": 288.4,
      "mix": {
        "coal": 36.3,
        "gas": 48.8,
        "oil": 1.6,
        "nuclear": 1.1,
        "hydro": 1.9,
        "wind": 4.2,
        "solar": 5.4,
        "biofuel": 0.7,
        "otherRenewables": 0.0
      },
      "region": "Asia",
      "subregion": "Eastern Asia",
      "lat": 23.5,
      "lng": 121.0,
      "restName": "Taiwan"
    },
    {
      "name": "Tajikistan",
      "iso": "TJK",
      "year": 2025,
      "generationTwh": 24.7,
      "mix": {
        "coal": 4.7,
        "gas": 1.0,
        "oil": 0.0,
        "nuclear": 0.0,
        "hydro": 94.3,
        "wind": 0.0,
        "solar": 0.0,
        "biofuel": 0.0,
        "otherRenewables": 0.0
      },
      "region": "Asia",
      "subregion": "Central Asia",
      "lat": 39.0,
      "lng": 71.0,
      "restName": "Tajikistan"
    },
    {
      "name": "Tanzania",
      "iso": "TZA",
      "year": 2024,
      "generationTwh": 8.8,
      "mix": {
        "coal": 0.0,
        "gas": 62.7,
        "oil": 4.3,
        "nuclear": 0.0,
        "hydro": 31.7,
        "wind": 0.0,
        "solar": 0.5,
        "biofuel": 0.8,
        "otherRenewables": 0.0
      },
      "region": "Africa",
      "subregion": "Eastern Africa",
      "lat": -6.0,
      "lng": 35.0,
      "restName": "Tanzania"
    },
    {
      "name": "Thailand",
      "iso": "THA",
      "year": 2025,
      "generationTwh": 188.2,
      "mix": {
        "coal": 17.8,
        "gas": 65.6,
        "oil": 0.1,
        "nuclear": 0.0,
        "hydro": 4.0,
        "wind": 1.8,
        "solar": 5.3,
        "biofuel": 5.4,
        "otherRenewables": 0.0
      },
      "region": "Asia",
      "subregion": "South-Eastern Asia",
      "lat": 15.0,
      "lng": 100.0,
      "restName": "Thailand"
    },
    {
      "name": "Trinidad and Tobago",
      "iso": "TTO",
      "year": 2024,
      "generationTwh": 9.6,
      "mix": {
        "coal": 0.0,
        "gas": 99.5,
        "oil": 0.4,
        "nuclear": 0.0,
        "hydro": 0.0,
        "wind": 0.0,
        "solar": 0.1,
        "biofuel": 0.0,
        "otherRenewables": 0.0
      },
      "region": "Americas",
      "subregion": "Caribbean",
      "lat": 11.0,
      "lng": -61.0,
      "restName": "Trinidad and Tobago"
    },
    {
      "name": "Tunisia",
      "iso": "TUN",
      "year": 2025,
      "generationTwh": 22.3,
      "mix": {
        "coal": 0.0,
        "gas": 95.0,
        "oil": 1.0,
        "nuclear": 0.0,
        "hydro": 0.0,
        "wind": 1.5,
        "solar": 2.5,
        "biofuel": 0.0,
        "otherRenewables": 0.0
      },
      "region": "Africa",
      "subregion": "Northern Africa",
      "lat": 34.0,
      "lng": 9.0,
      "restName": "Tunisia"
    },
    {
      "name": "Turkey",
      "iso": "TUR",
      "year": 2025,
      "generationTwh": 353.9,
      "mix": {
        "coal": 34.4,
        "gas": 22.1,
        "oil": 0.3,
        "nuclear": 0.0,
        "hydro": 16.2,
        "wind": 11.1,
        "solar": 10.5,
        "biofuel": 2.4,
        "otherRenewables": 3.0
      },
      "region": "Asia",
      "subregion": "Western Asia",
      "lat": 39.0,
      "lng": 35.0,
      "restName": "Türkiye"
    },
    {
      "name": "Turkmenistan",
      "iso": "TKM",
      "year": 2024,
      "generationTwh": 33.0,
      "mix": {
        "coal": 0.0,
        "gas": 100.0,
        "oil": 0.0,
        "nuclear": 0.0,
        "hydro": 0.0,
        "wind": 0.0,
        "solar": 0.0,
        "biofuel": 0.0,
        "otherRenewables": 0.0
      },
      "region": "Asia",
      "subregion": "Central Asia",
      "lat": 40.0,
      "lng": 60.0,
      "restName": "Turkmenistan"
    },
    {
      "name": "Uganda",
      "iso": "UGA",
      "year": 2024,
      "generationTwh": 5.8,
      "mix": {
        "coal": 0.0,
        "gas": 0.0,
        "oil": 2.9,
        "nuclear": 0.0,
        "hydro": 86.1,
        "wind": 0.0,
        "solar": 2.9,
        "biofuel": 8.1,
        "otherRenewables": 0.0
      },
      "region": "Africa",
      "subregion": "Eastern Africa",
      "lat": 1.0,
      "lng": 32.0,
      "restName": "Uganda"
    },
    {
      "name": "Ukraine",
      "iso": "UKR",
      "year": 2022,
      "generationTwh": 111.5,
      "mix": {
        "coal": 20.9,
        "gas": 6.4,
        "oil": 0.5,
        "nuclear": 55.7,
        "hydro": 9.9,
        "wind": 1.3,
        "solar": 4.6,
        "biofuel": 0.7,
        "otherRenewables": 0.0
      },
      "region": "Europe",
      "subregion": "Eastern Europe",
      "lat": 49.0,
      "lng": 32.0,
      "restName": "Ukraine"
    },
    {
      "name": "United Arab Emirates",
      "iso": "ARE",
      "year": 2024,
      "generationTwh": 177.3,
      "mix": {
        "coal": 0.0,
        "gas": 68.3,
        "oil": 0.0,
        "nuclear": 22.9,
        "hydro": 0.0,
        "wind": 0.1,
        "solar": 8.6,
        "biofuel": 0.1,
        "otherRenewables": 0.0
      },
      "region": "Asia",
      "subregion": "Western Asia",
      "lat": 24.0,
      "lng": 54.0,
      "restName": "United Arab Emirates"
    },
    {
      "name": "United Kingdom",
      "iso": "GBR",
      "year": 2025,
      "generationTwh": 292.3,
      "mix": {
        "coal": 0.1,
        "gas": 31.1,
        "oil": 4.4,
        "nuclear": 12.4,
        "hydro": 1.9,
        "wind": 29.4,
        "solar": 6.6,
        "biofuel": 14.1,
        "otherRenewables": 0.0
      },
      "region": "Europe",
      "subregion": "Northern Europe",
      "lat": 54.0,
      "lng": -2.0,
      "restName": "United Kingdom"
    },
    {
      "name": "United States",
      "iso": "USA",
      "year": 2025,
      "generationTwh": 4519.8,
      "mix": {
        "coal": 16.3,
        "gas": 40.0,
        "oil": 0.7,
        "nuclear": 17.4,
        "hydro": 5.3,
        "wind": 10.3,
        "solar": 8.6,
        "biofuel": 1.0,
        "otherRenewables": 0.4
      },
      "region": "Americas",
      "subregion": "North America",
      "lat": 38.0,
      "lng": -97.0,
      "restName": "United States"
    },
    {
      "name": "Uruguay",
      "iso": "URY",
      "year": 2025,
      "generationTwh": 11.9,
      "mix": {
        "coal": 0.0,
        "gas": 0.0,
        "oil": 2.2,
        "nuclear": 0.0,
        "hydro": 27.2,
        "wind": 40.6,
        "solar": 5.1,
        "biofuel": 24.9,
        "otherRenewables": 0.0
      },
      "region": "Americas",
      "subregion": "South America",
      "lat": -33.0,
      "lng": -56.0,
      "restName": "Uruguay"
    },
    {
      "name": "Uzbekistan",
      "iso": "UZB",
      "year": 2025,
      "generationTwh": 86.7,
      "mix": {
        "coal": 6.6,
        "gas": 72.3,
        "oil": 1.7,
        "nuclear": 0.0,
        "hydro": 7.3,
        "wind": 4.6,
        "solar": 7.5,
        "biofuel": 0.0,
        "otherRenewables": 0.0
      },
      "region": "Asia",
      "subregion": "Central Asia",
      "lat": 41.0,
      "lng": 64.0,
      "restName": "Uzbekistan"
    },
    {
      "name": "Venezuela",
      "iso": "VEN",
      "year": 2024,
      "generationTwh": 80.1,
      "mix": {
        "coal": 0.0,
        "gas": 4.5,
        "oil": 4.4,
        "nuclear": 0.0,
        "hydro": 91.1,
        "wind": 0.0,
        "solar": 0.0,
        "biofuel": 0.0,
        "otherRenewables": 0.0
      },
      "region": "Americas",
      "subregion": "South America",
      "lat": 8.0,
      "lng": -66.0,
      "restName": "Venezuela"
    },
    {
      "name": "Vietnam",
      "iso": "VNM",
      "year": 2025,
      "generationTwh": 310.0,
      "mix": {
        "coal": 48.3,
        "gas": 6.2,
        "oil": 0.2,
        "nuclear": 0.0,
        "hydro": 33.0,
        "wind": 4.6,
        "solar": 7.4,
        "biofuel": 0.3,
        "otherRenewables": 0.0
      },
      "region": "Asia",
      "subregion": "South-Eastern Asia",
      "lat": 16.16666666,
      "lng": 107.83333333,
      "restName": "Vietnam"
    },
    {
      "name": "Yemen",
      "iso": "YEM",
      "year": 2024,
      "generationTwh": 5.2,
      "mix": {
        "coal": 0.0,
        "gas": 1.1,
        "oil": 87.7,
        "nuclear": 0.0,
        "hydro": 0.0,
        "wind": 0.0,
        "solar": 11.2,
        "biofuel": 0.0,
        "otherRenewables": 0.0
      },
      "region": "Asia",
      "subregion": "Western Asia",
      "lat": 15.0,
      "lng": 48.0,
      "restName": "Yemen"
    },
    {
      "name": "Zambia",
      "iso": "ZMB",
      "year": 2024,
      "generationTwh": 19.7,
      "mix": {
        "coal": 10.8,
        "gas": 0.0,
        "oil": 1.7,
        "nuclear": 0.0,
        "hydro": 86.2,
        "wind": 0.0,
        "solar": 0.9,
        "biofuel": 0.4,
        "otherRenewables": 0.0
      },
      "region": "Africa",
      "subregion": "Eastern Africa",
      "lat": -15.0,
      "lng": 30.0,
      "restName": "Zambia"
    },
    {
      "name": "Zimbabwe",
      "iso": "ZWE",
      "year": 2024,
      "generationTwh": 10.3,
      "mix": {
        "coal": 42.9,
        "gas": 0.0,
        "oil": 0.0,
        "nuclear": 0.0,
        "hydro": 55.5,
        "wind": 0.0,
        "solar": 0.4,
        "biofuel": 1.2,
        "otherRenewables": 0.0
      },
      "region": "Africa",
      "subregion": "Eastern Africa",
      "lat": -20.0,
      "lng": 30.0,
      "restName": "Zimbabwe"
    }
  ]
};
